#cloud-config
package_update: true

runcmd:
    - export GRR_ARCH=$(if [ $(uname -p) = "x86_64" ]; then echo "amd64"; else echo "i386"; fi)
    - sudo wget http://172.16.0.9/swift/v1/prebuilt_client/grr_3.2.1.1_${GRR_ARCH}.deb -q -O /tmp/grr_3.2.1.1_${GRR_ARCH}.deb
    - sudo dpkg --unpack /tmp/grr_3.2.1.1_${GRR_ARCH}.deb
    - >- # labels are comma separated array, like label-1, label-2, label-3
      sudo sed -i "\$aClient.labels: [ {{ labels|join(', ') }} ]" /usr/lib/grr/grr_3.2.1.1_${GRR_ARCH}/grrd.yaml
    - sudo dpkg --configure grr
    - sudo apt-get install -f -y
    - sudo rm -f /tmp/grr_3.2.1.1_${GRR_ARCH}.deb