version: 2
jobs:
    api-unittest:
        docker:
            - image: circleci/python:3.6
              environment:
                  - POSTGRES_USER: ezsetup
                  - POSTGRES_PASSWORD: 123456
                  - POSTGRES_HOST: 127.0.0.1
                  - POSTGRES_PORT: 5432
                  - POSTGRES_POOL_MIN_CONN: 10
                  - POSTGRES_POOL_MAX_CONN: 100
                  - REDIS_HOST: 127.0.0.1
                  - REDIS_PORT: 6379
                  - REDIS_TOKEN_DB: 1
                  - REDIS_JOBS_DB: 2

            - image: circleci/postgres:9.6
              environment:
                  - POSTGRES_DB: ezsetup
                  - POSTGRES_USER: ezsetup
                  - POSTGRES_PASSWORD: 123456

            - image: redis:3.2

        steps:
            - checkout
            - run: | # init database
                    sudo apt install postgresql-client

                    TIMEOUT=5
                    until PGPASSWORD=123456 psql -h 127.0.0.1 -U ezsetup -d ezsetup -c "select 1" > /dev/null 2>&1 || [ $TIMEOUT -eq 0 ]; do
                      echo "Waiting for postgres server, $((TIMEOUT--)) remaining attempts..."
                      sleep 1
                    done

                    cat api/database/migrations/*.sql | PGPASSWORD=123456 psql -q -h 127.0.0.1 -p 5432 -U ezsetup -d ezsetup
            - run: sudo pip install pipenv
            - run:
                command: |
                    cd api
                    pipenv --python 3.6
                    pipenv install -d
            - run: 
                command: |
                    make test

workflows:
    version: 2
    test:
        jobs:
            - api-unittest

